# Start from the latest PolarisHQ integrationtester image
FROM 137462835382.dkr.ecr.us-west-1.amazonaws.com/integrationtester

ENV GOPATH /go

# Set the WORKDIR to the project path in your GOPATH, e.g. /go/src/github.com/Polarishq/ot-try
WORKDIR /go/src/github.com/Polarishq/ot-try

# Copy the source files into place
COPY . ./
