// Code generated by go-swagger; DO NOT EDIT.

package cleanup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/Polarishq/ot-try/models"
)

// CleanupNoContentCode is the HTTP code returned for type CleanupNoContent
const CleanupNoContentCode int = 204

/*CleanupNoContent successful operation

swagger:response cleanupNoContent
*/
type CleanupNoContent struct {
}

// NewCleanupNoContent creates CleanupNoContent with default headers values
func NewCleanupNoContent() *CleanupNoContent {

	return &CleanupNoContent{}
}

// WriteResponse to the client
func (o *CleanupNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

/*CleanupDefault Unexpected error

swagger:response cleanupDefault
*/
type CleanupDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewCleanupDefault creates CleanupDefault with default headers values
func NewCleanupDefault(code int) *CleanupDefault {
	if code <= 0 {
		code = 500
	}

	return &CleanupDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the cleanup default response
func (o *CleanupDefault) WithStatusCode(code int) *CleanupDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the cleanup default response
func (o *CleanupDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the cleanup default response
func (o *CleanupDefault) WithPayload(payload *models.Error) *CleanupDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the cleanup default response
func (o *CleanupDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CleanupDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
