// Code generated by go-swagger; DO NOT EDIT.

package cleanup

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/Polarishq/ot-try/models"
)

// CleanupReader is a Reader for the Cleanup structure.
type CleanupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CleanupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewCleanupNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewCleanupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewCleanupNoContent creates a CleanupNoContent with default headers values
func NewCleanupNoContent() *CleanupNoContent {
	return &CleanupNoContent{}
}

/*CleanupNoContent handles this case with default header values.

successful operation
*/
type CleanupNoContent struct {
}

func (o *CleanupNoContent) Error() string {
	return fmt.Sprintf("[POST /cleanup][%d] cleanupNoContent ", 204)
}

func (o *CleanupNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewCleanupDefault creates a CleanupDefault with default headers values
func NewCleanupDefault(code int) *CleanupDefault {
	return &CleanupDefault{
		_statusCode: code,
	}
}

/*CleanupDefault handles this case with default header values.

Unexpected error
*/
type CleanupDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the cleanup default response
func (o *CleanupDefault) Code() int {
	return o._statusCode
}

func (o *CleanupDefault) Error() string {
	return fmt.Sprintf("[POST /cleanup][%d] cleanup default  %+v", o._statusCode, o.Payload)
}

func (o *CleanupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
