// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi ot-try
Rest API definition for ot-try


    Schemes:
      http
    Host: ot-try-v1
    BasePath: /
    Version: v1

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
